services:
  db:
    image: postgres:17-alpine
    container_name: tienda_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    container_name: tienda_backend
    restart: always
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT_EXTERNAL}:${BACKEND_PORT_INTERNAL}"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    container_name: tienda_frontend
    restart: always
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT_EXTERNAL}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:

